spring:
  application:
    name: Cars


  datasource:
    url: jdbc:mysql://localhost:3306/Dk3Cars?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sharmakunal0090@gmail.com
    password: mscs twrh moba rplt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 9094