spring:
  application:
    name: Cars

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 150MB
      file-size-threshold: 2MB


  datasource:
    url: jdbc:mysql://localhost:3306/Dk3Cars?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dk3car@gmail.com
    password: vkwhkislvrsnscts
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  tomcat:
    max-swallow-size: 150MB
    max-http-form-post-size: 157286400
    basedir: target/tomcat
    threads:
      max: 200
      min-spare: 10
  port: 9094