package com.Dk3.Cars.service;

import com.Dk3.Cars.entity.Booking;
import com.Dk3.Cars.entity.LoanDetail;
import com.Dk3.Cars.entity.Sale;
import com.itextpdf.html2pdf.ConverterProperties;
import com.itextpdf.html2pdf.HtmlConverter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

@Service
public class PdfService {

    private static final DateTimeFormatter DF = DateTimeFormatter.ofPattern("dd MMM yyyy");
    private static final DateTimeFormatter DTF = DateTimeFormatter.ofPattern("dd MMM yyyy hh:mm a");
    private static final DecimalFormat MONEY = new DecimalFormat("#,##0.00");

    public byte[] generateInvoicePdf(Sale sale) throws IOException {
        return render("Tax Invoice", "Dealer Sales Invoice", "Generated by DK3 Cars for customer handover and accounting.",
                rows("Invoice Number", "INV-" + safeId(sale.getId()), "Invoice Date", fmt(sale.getSoldDate()), "Payment Mode", sale.getPaymentMode()),
                rows("Customer Name", sale.getCustomer() != null ? sale.getCustomer().getName() : null, "Email", sale.getCustomer() != null ? sale.getCustomer().getEmail() : null, "Mobile", sale.getCustomer() != null ? sale.getCustomer().getMobile() : null),
                rows("Vehicle", sale.getCar() != null ? sale.getCar().getBrand() + " " + sale.getCar().getModel() : null, "VIN / Chassis", sale.getCar() != null ? sale.getCar().getVin() : null, "Engine Number", sale.getCar() != null ? sale.getCar().getEngineNo() : null),
                rows("Vehicle Price", money(sale.getSellingPrice()), "Discount", "- " + money(sale.getDiscount()), "GST", money(sale.getGstAmount()), "Final Amount", money(sale.getTotalAmount())),
                "This invoice is intended for showroom records and customer reference.");
    }

    public byte[] generateBookingDocumentPdf(Booking b, String title, String body) throws IOException {
        return render(title, "Customer Booking Pack", body,
                rows("Document Ref", ref("BK", b.getId()), "Booking Date", fmt(b.getBookingDate()), "Booking Status", b.getWorkflowStatus(), "Expected Delivery", fmt(b.getExpectedDeliveryDate())),
                customerRows(b), vehicleRows(b), amountRows(b),
                "This showroom copy is generated from the DK3 Cars booking workflow.");
    }

    public byte[] generateInsurancePolicyPdf(Booking b) throws IOException {
        LocalDate start = pick(b.getDeliveryCompletedAt() != null ? b.getDeliveryCompletedAt().toLocalDate() : null, b.getExpectedDeliveryDate(), b.getBookingDate(), LocalDate.now());
        return render("Motor Insurance Certificate", "Private Car Package Policy", "Insurance coverage certificate issued as part of the vehicle delivery file.",
                rows("Policy Number", b.getInsurancePolicyNumber(), "Insurance Company", b.getInsuranceCompanyName(), "Coverage Period", fmt(start) + " to " + fmt(start.plusYears(1).minusDays(1)), "IDV", money(b.getCar() != null ? b.getCar().getPrice() : null)),
                customerRows(b), vehicleRows(b), rows("Premium Received", money(b.getInsuranceAmount()), "Third Party Cover", "Active", "Own Damage Cover", "Active"),
                "This document is a dealer-generated customer copy of the insurance details.");
    }

    public byte[] generateTemporaryRegistrationPdf(Booking b) throws IOException {
        LocalDate issue = LocalDate.now();
        return render("Temporary Registration Certificate", "Delivery Movement Approval", "Temporary registration generated for dealer delivery and customer handover.",
                rows("Temporary Registration No.", regNo(b), "Issuing Authority", b.getRtoAuthority(), "Issue Date", fmt(issue), "Valid Until", fmt(issue.plusDays(30))),
                customerRows(b), vehicleRows(b), rows("Road Tax Status", amtPositive(b.getRoadTaxAmount()) ? "Paid" : "Included", "RTO Application", "Submitted", "Form 20/21/22", "Submitted"),
                "This temporary registration copy is intended for showroom and customer reference.");
    }

    public byte[] generateRegistrationCertificatePdf(Booking b) throws IOException {
        return render("Registration Certificate", "Dealer Delivery Copy", "Structured RC-style document prepared for the customer delivery file.",
                rows("Registration Number", regNo(b), "Owner Name", customerName(b), "Address", customerAddress(b), "Issuing Authority", b.getRtoAuthority()),
                customerRows(b), vehicleRows(b), rows("Fuel Type", b.getCar() != null ? b.getCar().getFuelType() : null, "Color", b.getCar() != null ? b.getCar().getColor() : null, "Hypothecation", isLoan(b) ? "Applicable" : "Not Applicable"),
                "This is a showroom-generated RC-format copy. Official government validation depends on RTO processing.");
    }

    public byte[] generatePucCertificatePdf(Booking b) throws IOException {
        LocalDate issued = pick(b.getDeliveryCompletedAt() != null ? b.getDeliveryCompletedAt().toLocalDate() : null, b.getExpectedDeliveryDate(), LocalDate.now());
        return render("Pollution Under Control Certificate", "Vehicle Emission Compliance", "PUC certificate issued for customer handover with delivery documentation.",
                rows("Certificate Number", ref("PUC", b.getId()), "Issued On", fmt(issued), "Valid Until", fmt(issued.plusYears(1)), "Emission Norm", "BS6 Compliant"),
                customerRows(b), vehicleRows(b), rows("Registration Number", regNo(b), "Fuel Type", b.getCar() != null ? b.getCar().getFuelType() : null, "Compliance Status", "Pass"),
                "This customer copy reflects the PUC details captured during delivery readiness.");
    }

    public byte[] generateWarrantyBookletPdf(Booking b) throws IOException {
        LocalDate start = pick(b.getDeliveryCompletedAt() != null ? b.getDeliveryCompletedAt().toLocalDate() : null, b.getExpectedDeliveryDate(), LocalDate.now());
        LocalDate end = start.plusYears(amtPositive(b.getExtendedWarrantyAmount()) ? 5 : 3);
        return render("Warranty Booklet", "Customer Coverage Record", "Warranty booklet containing coverage summary, exclusions and service usage notes.",
                rows("Warranty Booklet No.", ref("WAR", b.getId()), "Coverage Start", fmt(start), "Coverage End", fmt(end), "Plan", amtPositive(b.getExtendedWarrantyAmount()) ? "Extended Warranty" : "Standard Warranty"),
                customerRows(b), vehicleRows(b), rows("Powertrain Coverage", "Included", "Electrical Coverage", "Included", "Roadside Assistance", "Included"),
                "Carry this booklet for warranty claims and service visits.");
    }

    public byte[] generateServiceBookPdf(Booking b) throws IOException {
        LocalDate start = pick(b.getDeliveryCompletedAt() != null ? b.getDeliveryCompletedAt().toLocalDate() : null, b.getExpectedDeliveryDate(), LocalDate.now());
        return render("Vehicle Service Book", "Maintenance Schedule", "Service record booklet with preventive maintenance schedule and workshop notes.",
                rows("Service Book No.", ref("SER", b.getId()), "Issuing Showroom", showroom(b), "Vehicle Owner", customerName(b)),
                customerRows(b), vehicleRows(b), rows("1st Service", fmt(start.plusMonths(1)) + " or 1,000 km", "2nd Service", fmt(start.plusMonths(6)) + " or 5,000 km", "3rd Service", fmt(start.plusMonths(12)) + " or 10,000 km", "4th Service", fmt(start.plusMonths(18)) + " or 20,000 km"),
                "Present this booklet at each scheduled service for stamping and service history updates.");
    }

    public byte[] generateDeliveryNotePdf(Booking b) throws IOException {
        return render("Vehicle Delivery Note", "Customer Handover Memo", "Signed delivery note confirming physical handover, document receipt and final vehicle verification.",
                rows("Delivery Note No.", ref("DLV", b.getId()), "Delivery Date", fmt(b.getDeliveryCompletedAt()), "Delivery Type", b.getDeliveryType(), "Time Slot", b.getDeliveryTimeSlot()),
                customerRows(b), vehicleRows(b), rows("Original Documents Verified", yn(b.getOriginalDocumentsVerified()), "Physical Verification Completed", yn(b.getPhysicalVerificationDone()), "Delivery Note Signed", yn(b.getDeliveryNoteSigned())),
                "Customer signature and acknowledgement are required on the physical handover copy.");
    }

    public byte[] generateRoadTaxReceiptPdf(Booking b) throws IOException {
        return render("Road Tax Receipt", "Statutory Tax Acknowledgement", "Receipt generated for the road tax amount collected during the booking and registration process.",
                rows("Receipt Number", ref("TAX", b.getId()), "State", b.getState(), "RTO Authority", b.getRtoAuthority(), "Payment Date", fmt(LocalDate.now())),
                customerRows(b), vehicleRows(b), rows("Road Tax Amount", money(b.getRoadTaxAmount()), "Registration Number", regNo(b), "Payment Status", "Received"),
                "This is a dealer-generated receipt aligned to the booking payment record.");
    }

    public byte[] generateFinalInvoicePdf(Booking b) throws IOException {
        return render("Final Tax Invoice / Sale Bill", "Customer Delivery Billing", "Final vehicle invoice issued after payment completion and delivery clearance.",
                rows("Invoice Number", ref("INV", b.getId()), "Sale Bill Number", ref("SB", b.getId()), "Invoice Date", fmt(LocalDate.now()), "Payment Mode", b.getPaymentMode()),
                customerRows(b), vehicleRows(b), finalAmountRows(b),
                "This invoice should be retained with the customer handover set.");
    }

    public byte[] generateFinanceSanctionLetterPdf(Booking b, LoanDetail loan) throws IOException {
        return render("Vehicle Finance Sanction Letter", "Retail Auto Loan Approval", "Loan sanction letter prepared for customer delivery and finance desk reference.",
                rows("Sanction Letter No.", ref("FIN", b.getId()), "Bank / NBFC", loan != null ? loan.getBankName() : null, "Approval Status", loan != null ? loan.getStatus() : "Pending", "Approval Date", loan != null ? fmt(loan.getApprovedAt()) : "Pending"),
                customerRows(b), vehicleRows(b), rows("On-Road Price", money(b.getTotalAmount()), "Down Payment", money(loan != null ? loan.getDownPaymentAmount() : b.getDownPaymentAmount()), "Sanctioned Amount", money(loan != null ? loan.getLoanAmount() : null), "Monthly EMI", money(loan != null ? loan.getEmiAmount() : null)),
                "Final disbursal remains subject to bank verification and document execution.");
    }

    public byte[] generateFinanceAgreementPdf(Booking b, LoanDetail loan) throws IOException {
        return render("Vehicle Finance Agreement Summary", "Hypothecation and Repayment Record", "Finance agreement summary issued with the customer loan document pack.",
                rows("Agreement Number", ref("AGR", b.getId()), "Lender", loan != null ? loan.getBankName() : null, "Borrower", customerName(b), "Execution Date", fmt(LocalDate.now())),
                customerRows(b), vehicleRows(b), rows("Loan Amount", money(loan != null ? loan.getLoanAmount() : null), "Tenure", loan != null && loan.getTenureMonths() != null ? loan.getTenureMonths() + " months" : null, "EMI", money(loan != null ? loan.getEmiAmount() : null), "Repayment Mode", "ECS / Auto Debit"),
                "This summary should be retained with the sanction letter and repayment schedule.");
    }

    private byte[] render(String title, String subtitle, String intro, List<Row> summary, List<Row> customer, List<Row> vehicle, List<Row> details, String note) throws IOException {
        StringBuilder html = new StringBuilder();
        html.append("<html><head><style>")
                .append("body{font-family:Helvetica,Arial,sans-serif;margin:24px;color:#172033;font-size:12px;}")
                .append(".sheet{border:1px solid #d7deea;border-radius:16px;overflow:hidden;}")
                .append(".top{padding:22px 24px;background:linear-gradient(135deg,#0f4c81,#1c7ed6);color:#fff;}")
                .append(".brand{font-size:24px;font-weight:700;letter-spacing:.8px;}.hero{font-size:22px;font-weight:700;margin:4px 0 6px;}.sub{font-size:12px;opacity:.92;}")
                .append(".body{padding:22px 24px 8px;}.intro{margin:0 0 16px;line-height:1.6;color:#364152;}")
                .append(".grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;}.section{border:1px solid #e3e8f0;border-radius:12px;padding:14px;background:#fbfcfe;margin-bottom:14px;}")
                .append(".section h3{margin:0 0 10px;color:#0f3f74;font-size:13px;text-transform:uppercase;letter-spacing:.6px;}")
                .append(".row{display:flex;justify-content:space-between;gap:12px;padding:6px 0;border-bottom:1px dashed #e8edf4;}.row:last-child{border-bottom:none;padding-bottom:0;}")
                .append(".label{font-weight:700;color:#334155;}.value{text-align:right;color:#0f172a;}.footer{padding:0 24px 24px;color:#5b6576;font-size:11px;line-height:1.6;}")
                .append("@page{size:A4;margin:18px;}</style></head><body><div class='sheet'><div class='top'><div class='brand'>DK3 CARS</div><div class='hero'>")
                .append(esc(title)).append("</div><div class='sub'>").append(esc(subtitle)).append("</div></div><div class='body'><p class='intro'>")
                .append(esc(intro)).append("</p>");
        section(html, "Document Summary", summary);
        html.append("<div class='grid'>");
        section(html, "Customer Details", customer);
        section(html, "Vehicle Details", vehicle);
        html.append("</div>");
        section(html, "Details", details);
        html.append("</div><div class='footer'>").append(esc(note)).append("</div></div></body></html>");
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        HtmlConverter.convertToPdf(html.toString(), out, new ConverterProperties());
        return out.toByteArray();
    }

    private void section(StringBuilder html, String title, List<Row> rows) {
        if (rows == null || rows.isEmpty()) return;
        html.append("<div class='section'><h3>").append(esc(title)).append("</h3>");
        for (Row row : rows) {
            html.append("<div class='row'><div class='label'>").append(esc(row.label())).append("</div><div class='value'>").append(esc(row.value())).append("</div></div>");
        }
        html.append("</div>");
    }

    private List<Row> customerRows(Booking b) {
        return rows("Customer Name", customerName(b), "Email", b.getCustomer() != null ? b.getCustomer().getEmail() : null, "Mobile", b.getCustomer() != null ? b.getCustomer().getMobile() : null, "Address", customerAddress(b), "PAN", b.getPanNumber(), "Aadhaar", aadhaar(b.getAadhaarNumber()));
    }

    private List<Row> vehicleRows(Booking b) {
        return rows("Vehicle", carName(b), "Variant", b.getCar() != null ? b.getCar().getVariant() : null, "VIN / Chassis", b.getCar() != null ? b.getCar().getVin() : null, "Engine Number", b.getCar() != null ? b.getCar().getEngineNo() : null, "Color", b.getCar() != null ? b.getCar().getColor() : null, "Fuel / Transmission", fuelTransmission(b));
    }

    private List<Row> amountRows(Booking b) {
        return rows("Booking Amount", money(b.getBookingAmount()), "On-Road Estimate", money(b.getTotalAmount()), "Paid Amount", money(b.getPaidAmount()), "Balance Amount", money(b.getRemainingAmount()));
    }

    private List<Row> finalAmountRows(Booking b) {
        return rows("Ex-Showroom Price", money(b.getCar() != null ? b.getCar().getPrice() : null), "GST", money(b.getGstAmount()), "RTO Charges", money(b.getRtoCharges()), "Road Tax", money(b.getRoadTaxAmount()), "Insurance", money(b.getInsuranceAmount()), "FASTag", money(b.getFastagCharges()), "Handling Charges", money(b.getHandlingCharges()), "Accessories", money(b.getAccessoriesAmount()), "Extended Warranty", money(b.getExtendedWarrantyAmount()), "TCS", money(b.getTcsAmount()), "Total Amount", money(b.getTotalAmount()));
    }

    private List<Row> rows(Object... vals) {
        List<Row> rows = new ArrayList<>();
        for (int i = 0; i + 1 < vals.length; i += 2) {
            String value = safe(vals[i + 1]);
            if (!"Not Available".equals(value)) rows.add(new Row(String.valueOf(vals[i]), value));
        }
        return rows;
    }

    private boolean isLoan(Booking b) { return b.getPaymentOption() != null && "Loan Required".equalsIgnoreCase(b.getPaymentOption()); }
    private boolean amtPositive(Double v) { return v != null && v > 0; }
    private String customerName(Booking b) { return b.getFullName() != null && !b.getFullName().isBlank() ? b.getFullName() : b.getCustomer() != null ? b.getCustomer().getName() : "Customer"; }
    private String customerAddress(Booking b) { return b.getAddress() != null && !b.getAddress().isBlank() ? (b.getAddress() + ", " + nz(b.getCity()) + ", " + nz(b.getState()) + " " + nz(b.getPinCode())).replaceAll("\\s+,", ",").trim() : b.getCustomer() != null ? b.getCustomer().getAddress() : "Not Available"; }
    private String carName(Booking b) { return b.getCar() == null ? "Vehicle not linked" : b.getCar().getBrand() + " " + b.getCar().getModel() + (b.getCar().getVariant() != null && !b.getCar().getVariant().isBlank() ? " " + b.getCar().getVariant() : ""); }
    private String fuelTransmission(Booking b) { return b.getCar() == null ? "Not Available" : safe(b.getCar().getFuelType()) + " / " + safe(b.getCar().getTransmission()); }
    private String showroom(Booking b) { return b.getCar() != null && b.getCar().getShowroom() != null ? b.getCar().getShowroom().getName() : "DK3 Cars Showroom"; }
    private String regNo(Booking b) { return b.getTemporaryRegistrationNumber() != null && !b.getTemporaryRegistrationNumber().isBlank() ? b.getTemporaryRegistrationNumber() : "MH-TEMP-" + safeId(b.getId()); }
    private String aadhaar(String value) { String d = value == null ? "" : value.replaceAll("\\D", ""); return d.length() >= 4 ? "XXXX-XXXX-" + d.substring(d.length() - 4) : safe(value); }
    private String money(Double value) { return "Rs. " + MONEY.format(value == null ? 0D : value); }
    private String money(double value) { return "Rs. " + MONEY.format(value); }
    private String fmt(LocalDate value) { return value == null ? "Not Available" : value.format(DF); }
    private String fmt(LocalDateTime value) { return value == null ? "Not Available" : value.format(DTF); }
    private LocalDate pick(LocalDate... dates) { for (LocalDate d : dates) if (d != null) return d; return LocalDate.now(); }
    private String yn(Boolean value) { return Boolean.TRUE.equals(value) ? "Yes" : "No"; }
    private String safe(Object value) { String s = value == null ? "" : String.valueOf(value).trim(); return s.isEmpty() ? "Not Available" : s; }
    private String nz(String value) { return value == null ? "" : value; }
    private String safeId(Long id) { return id == null ? "0000" : String.format("%04d", id); }
    private String ref(String prefix, Long id) { return prefix + "/" + LocalDate.now().getYear() + "/" + safeId(id); }
    private String esc(String text) { return safe(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;"); }

    private record Row(String label, String value) {}
}
